### ISSUE TITLE
Prism.js

### ISSUE THREAD

**Issue by amenolo** [qbin-io/qbin#1]
Cool project!
I'd like to solve this issue...

`Prism.js initialization failed: giving up on the following error: dial unix /tmp/prismjs.sock: connect: no such file or directory`

Any hint?

Thanks

[BTW any chance in getting source code of original one (qbin.io)?]

**Comment by moqmar** [comment]
The only thing missing without prism-server is syntax highlighting, but you can fix this by starting the prism.js server with `node prism-server` from the qbin repository, or by using the `launch.sh` to launch qbin.

The unix socket prism-server was hard-coded to `/tmp/prismjs.sock`, I added a configuration option for that though, and also updated the documentation to include how this works.

Quick explanation for why this is needed: As I want the syntax highlighting in the editor to be exactly the same as the one generated by the server, I'm used prism.js there, which is running on a node.js server that interacts with the qbin server using unix sockets. The alternatives would be to either rewrite prism.js in Golang, which is a lot of work (maybe that's another project for later), or to use V8 from Go directly, which is as far as I have tried not that easy and would require other libraries and/or binaries that are even harder to install.

**Comment by moqmar** [comment]
For the old version, I currently don't really have an up-to-date repository of that. It was node.js, used MongoDB at some point, which was later changed to Sqlite. It's really not that much of a great example for a project, so I'll keep the code for myself for now and delete it as soon as this version is deployed to qbin.io.

**Comment by amenolo** [comment]
Very appreciated answers!

Well I'd like to use syntax highlighting in fact, and yes I had totally missed the all "launch.sh/node prism-server" matter , so I just tested, and...sorry to bother you further, but no luck in first place...

```
root@test:~# ./launch.sh
prism-server started at: /tmp/prismjs.sock
2017/12/09 13:40:40 Prism.js initialization failed: giving up on the following error: dial unix /tmp/prismjs.sock: connect: no such file or directory
13:40:40.229 Connect: NOTI  Connecting to database at root:***@tcp(127.0.0.1)/qbin
13:40:40.270 Connect: NOTI  Database version: 5.7.20-0ubuntu0.16.04.1
13:40:40.319 StartTCP: WARN  TCP server is not yet implemented.
13:40:40.324 StartHTTP: NOTI  HTTP server starting on :8000, you should be able to reach it at http://127.0.0.1:8000
```

For the record in tmp dir is being created

`srwxr-xr-x  1 root root    0 dic  9 13:40 prism-server.sock=`

which I guess is the standard behavior, although not 100% sure, since I'm sadly not a programmer kind of guy :-(

**Comment by moqmar** [comment]
Could you try pulling again and run `git submodule update` to update the backend files before building. You can also go to "backend" and run `git checkout master` to get the newest files.
